#!/bin/bash

# Copy scripts from $USER/sbin to /usr/local/sbin,
# change ownership and group to root,
# and set appropriate permissions
# Run script as root

USER=istjohn

shopt -s extglob
cp -r /home/${USER}/sbin/!(.git|LICENSE) /usr/local/sbin

